### ISSUE TITLE
Retarget Chance in settings.yml can retarget creative mode players

### ISSUE THREAD

**Issue by Lecer69** [kangarko/Boss#1186]
it can retarget the creative mode players. it should only works on survival & adventure mode.

config:
```yml
Fighting:
  
  # When you hit Boss who's already attacking someone else, enter the chance that it'll chase you.
  Retarget_Chance: 100%
  ```
