### ISSUE TITLE
Bosses do not spawn in custom worlds [1.21.4 Paper]

### ISSUE THREAD

**Issue by Veyjinn** [kangarko/Boss#1381]
Hi! 

Bosses are spawning in certain worlds but in others not. To spawn the bosses I use the **Spawn Near Players SpawnRule** I've checked the Common Issues article on Wiki and also tried to get some information out of the debug and it says:

`[SpawnRule=EndMiteSpawn] Not running due to biome chance (0.0% in null) did not pass`

In this case I wanted to make an Endermite to spawn near players in the End, which is generated by Terra with the community addon ReimagEnd. I'm using the Terra Worldgen Plugin and I'm working on a multiverse based server with many worlds. Some of them of them are custom generated. Guessing from the debug it says that I've set the biome spawn chance to 0, but I didn't. I've created a completely fresh spawn rule and normally that makes the boss spawn like crazy when enabling it. But in this case its completely silent. I've tried it to spawn on one other world and it worked just fine. 

If it might help I can try to spawn it on a blank server to see if the problem is related to the custom world generation.

**Comment by Veyjinn** [comment]
Yep, I can confirm that this issue is related to custom worlds. I've tested it on a fresh server - same problem

**Comment by kangarko** [comment]
Just to verify is the world NOT using any spaces or special letters? What is its name exactly?

**Comment by Veyjinn** [comment]
The world is called "End" with a capital letter.

**Comment by kangarko** [comment]
Thanks for confirming, I left office today and will be getting back to you in 1-2d.

**Comment by kangarko** [comment]
Okay so I setup multiversecore 5 environment on 1.21.5 and unfortunately cant reproduce:

![a](https://i.imgur.com/27bsdJ5.png)

Can you ensure all of your biomes have chance set to 1? You can just copy my rule yaml and adjust the Bosses and Worlds keys:

```yaml
#  -------------------------------------------------------------------------------------------------
#  This is a spawn rule configuration file. We strongly recommend only editing it using our GUI.
#  MineAcademy.org is not responsible for data loss or thermonuclear war from mistakes in your edit.
#  -------------------------------------------------------------------------------------------------

Block_Radius: 30
Worlds:
  world: 1.0
  flat: 1.0
  End: 1.0
Biomes:
  BADLANDS: 1.0
  BADLANDS_PLATEAU: 1.0
  BAMBOO_JUNGLE: 1.0
  BASALT_DELTAS: 1.0
  BEACH: 1.0
  BIRCH_FOREST: 1.0
  BIRCH_FOREST_HILLS: 1.0
  CHERRY_GROVE: 1.0
  COLD_OCEAN: 1.0
  CRIMSON_FOREST: 1.0
  CUSTOM: 1.0
  DARK_FOREST: 1.0
  DEEP_COLD_OCEAN: 1.0
  DEEP_DARK: 1.0
  DEEP_FROZEN_OCEAN: 1.0
  DEEP_LUKEWARM_OCEAN: 1.0
  DEEP_OCEAN: 1.0
  DESERT: 1.0
  DRIPSTONE_CAVES: 1.0
  END_BARRENS: 1.0
  END_HIGHLANDS: 1.0
  END_MIDLANDS: 1.0
  ERODED_BADLANDS: 1.0
  FLOWER_FOREST: 1.0
  FOREST: 1.0
  FROZEN_OCEAN: 1.0
  FROZEN_PEAKS: 1.0
  FROZEN_RIVER: 1.0
  GIANT_SPRUCE_TAIGA: 1.0
  GIANT_SPRUCE_TAIGA_HILLS: 1.0
  GIANT_TREE_TAIGA: 1.0
  GIANT_TREE_TAIGA_HILLS: 1.0
  GROVE: 1.0
  ICE_SPIKES: 1.0
  JAGGED_PEAKS: 1.0
  JUNGLE: 1.0
  LUKEWARM_OCEAN: 1.0
  LUSH_CAVES: 1.0
  MANGROVE_SWAMP: 1.0
  MEADOW: 1.0
  MODIFIED_BADLANDS_PLATEAU: 1.0
  MODIFIED_GRAVELLY_MOUNTAINS: 1.0
  MODIFIED_JUNGLE_EDGE: 1.0
  MODIFIED_WOODED_BADLANDS_PLATEAU: 1.0
  MOUNTAIN_EDGE: 1.0
  MUSHROOM_FIELDS: 1.0
  MUSHROOM_FIELD_SHORE: 1.0
  NETHER_WASTES: 1.0
  OCEAN: 1.0
  OLD_GROWTH_BIRCH_FOREST: 1.0
  OLD_GROWTH_PINE_TAIGA: 1.0
  OLD_GROWTH_SPRUCE_TAIGA: 1.0
  PALE_GARDEN: 1.0
  PLAINS: 1.0
  RIVER: 1.0
  SAVANNA: 1.0
  SAVANNA_PLATEAU: 1.0
  SHATTERED_SAVANNA_PLATEAU: 1.0
  SMALL_END_ISLANDS: 1.0
  SNOWY_BEACH: 1.0
  SNOWY_MOUNTAINS: 1.0
  SNOWY_PLAINS: 1.0
  SNOWY_SLOPES: 1.0
  SNOWY_TAIGA: 1.0
  SNOWY_TAIGA_MOUNTAINS: 1.0
  SOUL_SAND_VALLEY: 1.0
  SPARSE_JUNGLE: 1.0
  STONY_PEAKS: 1.0
  STONY_SHORE: 1.0
  SUNFLOWER_PLAINS: 1.0
  SWAMP: 1.0
  TAIGA: 1.0
  TAIGA_MOUNTAINS: 1.0
  TALL_BIRCH_FOREST: 1.0
  TALL_BIRCH_HILLS: 1.0
  THE_END: 1.0
  THE_VOID: 1.0
  WARM_OCEAN: 1.0
  WARPED_FOREST: 1.0
  WINDSWEPT_FOREST: 1.0
  WINDSWEPT_GRAVELLY_HILLS: 1.0
  WINDSWEPT_HILLS: 1.0
  WINDSWEPT_SAVANNA: 1.0
  WOODED_BADLANDS: 1.0
Regions_2:
  BOSS: {}
  RESIDENCE: {}
  FACTIONS: {}
  TOWNY: {}
  LANDS: {}
  WORLDGUARD: {}
Regions_Enabled: false
Regions_Whitelist: true
Type: PERIOD
Enabled: true
Bosses:
- Endermite
Delay: '0'
Days:
- THURSDAY
- SATURDAY
- SUNDAY
- TUESDAY
- FRIDAY
- MONDAY
- WEDNESDAY
Months:
- SEPTEMBER
- JULY
- AUGUST
- NOVEMBER
- APRIL
- JANUARY
- FEBRUARY
- JUNE
- OCTOBER
- MARCH
- DECEMBER
- MAY
Rain: false
Thunder: false
Chance: 1.0
Last_Executed: -1

```
