### ISSUE TITLE
Pillager based mob is not attacking

### ISSUE THREAD

**Issue by skerit** [kangarko/Boss#439]
I'm trying to make a custom mob based on a pillager, but it's not attacking me. Not during the day & not at night. Here's the config:

```yml
Type: PILLAGER
Custom_Name: Bandit
No_Spawn_Permission_Message: ''
Health: 30
Dropped_Exp: default
Potions:
- SPEED 1
Specific_Settings:
  Display_Name: true
  Glowing: false
  Invulnerable: false
  Gravity: true
  Can_Pickup_Items: true
  Silent: false
  Targetable: true
  Despawn_When_Far_Away: true
  Auto_Target: true
Attributes:
  Armor Toughness: 0.0
  Knockback Resistance: 0.0
  Follow Range: 32.0
  Armor: 2.0
  Movement Speed: 0.3499999940395355
  Attack Damage: 5.0
Skills: '[]'
Death:
  Commands: '[]'
  Commands_For_Players: '[]'
  Reinforcements:
    Vanilla: '[]'
    Boss: '[]'
  Lightning: false
  Kill_Riding_Entity: true
  Inventory_Drops:
    Enabled: false
    Player_Limit: 5
    Time_Limit_Seconds: 10
Spawn:
  Commands: '[]'
Spawning:
  Worlds: {}
  Biomes: {}
  Regions:
    Boss: []
    Towny: []
    Factions: []
    Residence: []
    Blacklist: false
    WorldGuard:
    - Keep_Inside: true
      Limit: -1
      Name: bandit_camp
  Conditions:
    Rain: false
    Thunder: false
    Light: 0 - 15
    Time: 0 - 24000
    Height: 0 - 256
    Spawn_Under_Water: false
Sounds:
  Debug: false
  Remapped: {}
Riding: ''
Riding_Boss: ''
Spawner_Egg:
  Lore:
  - ' '
  - '&2&l< &7Left click for menu'
  - '&2&l> &7Right click to summon'
  Material: COD_SPAWN_EGG
  Glow: true
  Name: '&rSpawn {boss}'
Natural_Drops: false
Single_Drops: false
Damage_Multiplier: 1.0
Equipment:
  BOOTS:
    dropChance: 0.0
  Allow_Random: false
```
