### ISSUE TITLE
Ability to change name displayed on the Boss Egg in player inventory 

### ISSUE THREAD

**Issue by LeehamElectronics** [kangarko/Boss#624]
Pretty simple request, the reason being is because I like to name all of my mobs without formatting or fancy colors when I am creating them, however I am using Boss spawn eggs in my mini games shops and I want to change the name of the eggs when the player is holding them. I know we can change the display name, but it would be nice if we had the option to change the display name of the boss eggs lore / item name when holding it without changing the name of its actual file.

Here is an example:
I create my boss: /boss new bedwars_super_creeper
I change its display name to "&3Super Creeper!"
I now want to change the item name displayed in the players inventory to "&eSuper Creeper"

Let me know what you think.
Thanks

**Comment by LeehamElectronics** [comment]
Here is my suggestion on how to easily fix the issue:
```
Egg_Spawning:
  Max_Distance: 60
  Air_Spawn: true
  Spawn_If_Event_Cancelled: true
  Check_Regions: false
  Enforce_Latest_Egg_Version: false
  Item:
    Name: '&rSpawn {boss}'
    Material: MONSTER_EGG
    Glow: true
    Lore:
    - ' '
    - '&2&l< &7Left click for menu'
    - '&2&l> &7Right click to summon'
```

Instead of Name: '&rSpawn {boss}' in the config
Add the option to use Name: '&rSpawn {boss_display_name}'
So it will show the display name of the boss rather than its actual name.
