### ISSUE TITLE
1.18.1: Mounts removing itself from config file (ver 4.2.1)

### ISSUE THREAD

**Issue by phatrick17** [kangarko/Boss#995]
On Paper build 197

Boss mounts are removed from boss config file upon server restart or plugin reload.

Example:

```
Riding:
  Vanilla: []
  Boss:
  - BOSSNAME
  Remove_On_Death: true
```
turns into this after server restart

```
Riding:
  Vanilla: []
  Boss: []
  Remove_On_Death: true
```

Vanilla mounts work and are not removed from config.

**Comment by phatrick17** [comment]
Okay, so I _renamed my mount_ to something different and it fixed the issue.

Before my bosses were named:

**Boss:** PillagerGunman
**Mount:** PillagerGunmanMount
```
PillagerGunman.yml

Riding:
  Vanilla: []
  Boss:
  - PillagerGunmanMount
  Remove_On_Death: true
```

After changing it to:
**Boss:** PillagerGunman
**Mount:** MOUNTPILLAGERGUNNER
```
PillagerGunman.yml

Riding:
  Vanilla: []
  Boss:
  - MOUNTPILLAGERGUNNER
  Remove_On_Death: true
```

It no longer auto deletes the setting.
