### ISSUE TITLE
1.18.1 - boss mounts config removal

### ISSUE THREAD

**Issue by phatrick17** [kangarko/Boss#996]
REPOST TICKET BC I ACCIDENTALLY CLOSED IN CASE YOU WANNA SEE SRRY ITS NOT SPAM :c

On Paper build 197

Boss mounts are removed from boss config file upon server restart or plugin reload.

Example:

```
Riding:
  Vanilla: []
  Boss:
  - BOSSNAME
  Remove_On_Death: true
```
turns into this after server restart

```
Riding:
  Vanilla: []
  Boss: []
  Remove_On_Death: true
```

____________________________________________________________________________________________________________________________

Okay, so I _renamed my mount_ to something different and it fixed the issue.

Before my bosses were named:

**Boss:** PillagerGunman
**Mount:** PillagerGunmanMount
```
PillagerGunman.yml

Riding:
  Vanilla: []
  Boss:
  - PillagerGunmanMount
  Remove_On_Death: true
```

After changing it to:

**Boss:** PillagerGunman
**Mount:** _MOUNTPILLAGERGUNNER_
```
PillagerGunman.yml

Riding:
  Vanilla: []
  Boss:
  - MOUNTPILLAGERGUNNER
  Remove_On_Death: true
```

It no longer auto deletes the setting.
